-- Manual Parallel Execution Demo
-- Update <YOUR_WORKSPACE_HASH> with your workspace hash
-- Open 2 worksheets and run both commands at the same time

USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

-- Worksheet 1: TechCorp
EXECUTE NOTEBOOK PROJECT DEMO_DB.PUBLIC.CARBON_EMISSIONS_PROJECT
  MAIN_FILE = 'snow://workspace/<YOUR_WORKSPACE_HASH>/carbon_emissions_calculator.ipynb'
  COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
  QUERY_WAREHOUSE = 'CONTAINER_RUNTIME_WH'
  RUNTIME = 'V2.2-CPU-PY3.11'
  ARGUMENTS = 'TechCorp'
  REQUIREMENTS_FILE = 'snow://workspace/<YOUR_WORKSPACE_HASH>/requirements.txt'
  EXTERNAL_ACCESS_INTEGRATIONS = ('ALLOW_ALL_INTEGRATION');

-- Worksheet 2: ManufactureCo
EXECUTE NOTEBOOK PROJECT DEMO_DB.PUBLIC.CARBON_EMISSIONS_PROJECT
  MAIN_FILE = 'snow://workspace/<YOUR_WORKSPACE_HASH>/carbon_emissions_calculator.ipynb'
  COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
  QUERY_WAREHOUSE = 'CONTAINER_RUNTIME_WH'
  RUNTIME = 'V2.2-CPU-PY3.11'
  ARGUMENTS = 'ManufactureCo'
  REQUIREMENTS_FILE = 'snow://workspace/<YOUR_WORKSPACE_HASH>/requirements.txt'
  EXTERNAL_ACCESS_INTEGRATIONS = ('ALLOW_ALL_INTEGRATION');

-- View Results
SELECT 
    COMPANY_NAME,
    SCOPE,
    TOTAL_EMISSIONS_TCO2E,
    EXECUTION_TIME_SECONDS,
    EXECUTION_TIMESTAMP
FROM EMISSIONS_RESULTS
WHERE EXECUTION_TIMESTAMP >= DATEADD(MINUTE, -30, CURRENT_TIMESTAMP())
ORDER BY EXECUTION_TIMESTAMP DESC, COMPANY_NAME, SCOPE;

-- Summary by company
WITH latest_executions AS (
    SELECT 
        COMPANY_NAME,
        MAX(EXECUTION_TIMESTAMP) AS latest_execution
    FROM EMISSIONS_RESULTS
    GROUP BY COMPANY_NAME
)
SELECT 
    r.COMPANY_NAME,
    SUM(r.TOTAL_EMISSIONS_TCO2E) AS TOTAL_EMISSIONS_TCO2E,
    MAX(r.EXECUTION_TIME_SECONDS) AS EXECUTION_TIME_SECONDS,
    MAX(r.EXECUTION_TIMESTAMP) AS EXECUTION_TIMESTAMP
FROM EMISSIONS_RESULTS r
INNER JOIN latest_executions le 
    ON r.COMPANY_NAME = le.COMPANY_NAME 
    AND r.EXECUTION_TIMESTAMP = le.latest_execution
GROUP BY r.COMPANY_NAME
ORDER BY TOTAL_EMISSIONS_TCO2E DESC;

-- Executions by minute
SELECT 
    DATE_TRUNC('MINUTE', EXECUTION_TIMESTAMP) AS EXECUTION_MINUTE,
    COUNT(DISTINCT COMPANY_ID) AS COMPANIES_PROCESSED
FROM EMISSIONS_RESULTS
WHERE EXECUTION_TIMESTAMP >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('MINUTE', EXECUTION_TIMESTAMP)
ORDER BY EXECUTION_MINUTE DESC;

-- Performance Comparison: Sequential vs Parallel

SELECT 
    'Sequential Execution (est.)' AS EXECUTION_TYPE,
    SUM(EXECUTION_TIME_SECONDS) AS TOTAL_TIME_SECONDS,
    SUM(EXECUTION_TIME_SECONDS) / 60 AS TOTAL_TIME_MINUTES
FROM EMISSIONS_RESULTS
WHERE EXECUTION_TIMESTAMP >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())

UNION ALL

SELECT 
    'Parallel Execution (actual)' AS EXECUTION_TYPE,
    MAX(EXECUTION_TIME_SECONDS) AS TOTAL_TIME_SECONDS,
    MAX(EXECUTION_TIME_SECONDS) / 60 AS TOTAL_TIME_MINUTES
FROM EMISSIONS_RESULTS
WHERE EXECUTION_TIMESTAMP >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP());
